---
- name: Configure IP Address on Interface
  hosts: R1
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure IP address on interface
      ios_config:
        lines:
          - ip address 10.1.1.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet 0/1